/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import src.BLL;
import src.Project;

/**
 *
 * @author Asad Bin Khalid
 */
public class SearchProject extends javax.swing.JFrame {

    /**
     * Creates new form SearchProject
     */
    private BLL bll;
    public SearchProject() {
        initComponents();
        bll = BLL.getBllInstance();
        viewProjectButton.setVisible(false);
        projectNameExistsField.setVisible(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        SearchProjectLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchProjectName = new javax.swing.JTextField();
        searchButtonName = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchProjectTeam = new javax.swing.JTextField();
        searchButtonTeam = new javax.swing.JButton();
        projectNameExistsField = new javax.swing.JLabel();
        viewProjectButton = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        SearchProjectLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchProjectLabel.setText("Search Project");

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Project Name:");

        searchProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProjectNameActionPerformed(evt);
            }
        });

        searchButtonName.setText("Search");
        searchButtonName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonNameMouseClicked(evt);
            }
        });

        jLabel2.setText("Enter Team Lead Name:");

        searchProjectTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProjectTeamActionPerformed(evt);
            }
        });

        searchButtonTeam.setText("Search");
        searchButtonTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonTeamMouseClicked(evt);
            }
        });
        searchButtonTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonTeamActionPerformed(evt);
            }
        });

        projectNameExistsField.setBackground(new java.awt.Color(255, 255, 255));
        projectNameExistsField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        projectNameExistsField.setText("No project found");
        projectNameExistsField.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        viewProjectButton.setText("View Project Details");
        viewProjectButton.setActionCommand("View Details");
        viewProjectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewProjectButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(backButton)
                        .addGap(191, 191, 191)
                        .addComponent(SearchProjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchProjectName)
                            .addComponent(searchProjectTeam)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 214, Short.MAX_VALUE)))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButtonName)
                    .addComponent(searchButtonTeam))
                .addGap(160, 160, 160))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(projectNameExistsField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(viewProjectButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchProjectLabel)
                    .addComponent(backButton))
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButtonName))
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProjectTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButtonTeam))
                .addGap(52, 52, 52)
                .addComponent(projectNameExistsField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(viewProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchProjectTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProjectTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProjectTeamActionPerformed

    private void searchProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProjectNameActionPerformed

    private void searchButtonNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonNameMouseClicked
        // TODO add your handling code here:
        
        String projectName = searchProjectName.getText();
        
        if(!projectName.equals("")){
        
           project  = bll.searchProject(projectName);
           
           if(project!=null){
               
                projectNameExistsField.setText(" Project Found: " + projectName );
               projectNameExistsField.setVisible(true);

                viewProjectButton.setVisible(true);
           }
           else{
                projectNameExistsField.setText("No Projct Found");
               projectNameExistsField.setVisible(true);
               
           }
           
        }

    }//GEN-LAST:event_searchButtonNameMouseClicked

    private void searchButtonTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonTeamActionPerformed

    private void searchButtonTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonTeamMouseClicked

        // TODO add your handling code here:
        String teamLead = searchProjectTeam.getText();
        
        if(!teamLead.equals("")){
        
           project = bll.searchProjectByTeamLead(teamLead);
           
           if(project!=null){
               
                projectNameExistsField.setText(project.getName() +" Found");
                viewProjectButton.setVisible(true);
           }
           else{
            projectNameExistsField.setVisible(true);
           }
        }


    }//GEN-LAST:event_searchButtonTeamMouseClicked
      private Project project = null;
    private void viewProjectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProjectButtonMouseClicked
        // TODO add your handling code here:
        ViewProjectDetails page2 = new ViewProjectDetails(project);
        page2.start();
        this.setVisible(false);
        
    }//GEN-LAST:event_viewProjectButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
       ManagerHome page = new ManagerHome();
        page.start();
        this.setVisible(false);
    }//GEN-LAST:event_backButtonMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SearchProjectLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel projectNameExistsField;
    private javax.swing.JButton searchButtonName;
    private javax.swing.JButton searchButtonTeam;
    private javax.swing.JTextField searchProjectName;
    private javax.swing.JTextField searchProjectTeam;
    private javax.swing.JButton viewProjectButton;
    // End of variables declaration//GEN-END:variables
}
